# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969907c029746f99fd331d0856d03e1d87a60658902417e80d574cc9772723f2c44b3a135689f14949ed0a22b87ab1cbbd95f46b2e2de889aeaae40733002a1d

test:
  secret_key_base: 10671fa7e8a5b5b2f3bf46a670548d82278122ebccfb036716ecb3262ccee25821b9a15cb6acb2d6dc52d1cc45582a35654f1a5ed7cb8156ca67b5077f88eb09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
